version: '3.9'
services:
  pgvector:
    container_name: pgvector
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pgvector
      POSTGRES_USER: pgvector
      POSTGRES_PASSWORD: pgvector
